### ISSUE TITLE
Service mapping

### ISSUE THREAD

**Issue by Cofybreak** [su1s/e2m3u2bouquet#100]
If move service to another category, it is always at the end of the list

**Comment by DougMac** [comment]
If you move it to a new custom category you should be able to control the ordering. As you've noted if you move to an existing category it will go to the end

**Comment by Cofybreak** [comment]
Will be more convenient if you do not have to create a new category just to be able to rearrange 3 additional channels

**Comment by DougMac** [comment]
That's not possible at the moment.

Feel free to submit a patch that implements this and we will review.
