### ISSUE TITLE
Plugin not downloading M3U

### ISSUE THREAD

**Issue by lincsat** [su1s/e2m3u2bouquet#101]
This is an interesting one. The plugin will not download the M3U from one of my servers but if I invoke the e2m3u2bouquet.py from the command line, then it downloads the M3U just fine.

I'm only a Python novice and can't see anything but is there something different in the call from the plugin to the call from the command line?

**Comment by lincsat** [comment]
The v83 pre-release does seem to fix this issue, so I will close

**Comment by KodiJambo** [comment]
Having same issue, anywhere I could get pre release?

**Comment by lincsat** [comment]
From Releases - https://github.com/su1s/e2m3u2bouquet/releases/tag/v0.8.3

**Comment by lincsat** [comment]
Reopening as it's happening again. When running from the command line it takes 5-10 seconds to start the download of the M3U, when running the plugin it seems to give up after 1-2 secs. I don't know why, I'm just guessing it's something to do with the DDoS protection or whatever you call the cloudflare replacement that they are using.

**Comment by DougMac** [comment]
There should't be any different between the script and plugin so that's strange. If you're willing to provide the playlist we can investigate further. Get in touch via the contact form on the Suls website.

**Comment by lincsat** [comment]
That server has now switched from Streaminy to the new XC and the issue has gone, so I'll close this again.
