### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Jes0** [su1s/e2m3u2bouquet#104]
I get this error when script is trying to parse a non utf-8 m3u file:

----Parsing m3u file----
Traceback (most recent call last):
  File "./e2m3u2bouquet.py", line 1692, in <module>
    sys.exit(main())
  File "./e2m3u2bouquet.py", line 1680, in main
    raise e
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 5: invalid continuation byte

**Comment by DougMac** [comment]
Should be fixed in in [v0.8.5](https://github.com/su1s/e2m3u2bouquet/releases/latest). If not please reopen this issue
