### ISSUE TITLE
Crashing while trying to parse m3u file

### ISSUE THREAD

**Issue by skywalker0582** [su1s/e2m3u2bouquet#106]
Hello,

I have this issue (Both on V.0.8.3 & previous 0.8.2)

I Installed the plugin normally,
Inserting my username pass etc.
Everything seems ok as it downloads the m3u file,
but when it comes to parsing m3u file it stays on that screen for about 3-4 mins trying 
(the gear indicating that the box is trying and busy its there)
And then everytime it crashes my box and E2 restarts and nothing has happened.
I disabled the epg import feature also, updated my box but still the same.
My m3u file is fine cause when i generate the links with a html file that i found on a forum and import them on userbouquet.favourites.tv manually they work fine (as on VLC/PC)

PS* they used to work fine for about one year with the same provider.
(the only thing that was changed was the m3u file size the last time)

M3U file seems to be really big maybe thats the issue (?):
16MB
126763 - lines
10591  - Live TV streams
52790  - VOD

My Box:
Dm800se clone on Latest openPLI7.1 (Same issue with openPLI 7 )

**Comment by BliNeR-KeY** [comment]
hahha. DM800SE need to extraxt 16MB... LOL
V.0.8.2 and V.0.8.3 working well. 
You need to upgrade your decoder. or maybe memory ram (swap)
because i think no have more memory for extract data. 
Please when say Crash. need to post a crash log.

**Comment by skywalker0582** [comment]
Idk, you may be right. I  was thinking the same thing. But i am not sure. Thats why i opened an issue here. 
And about the crash log file, there is none  Revelant . ( I found the crash log file but there is no crash logs there considering this matter )
So it probably just restarts my E2 interface.

**Comment by BliNeR-KeY** [comment]
bro. e2m3u2bouquet working well. trust me.  Please try to upgrade your old 800SE maybe only swap 
but dhis is not e2m3u2bouquet issue.

**Comment by skywalker0582** [comment]
You were right.
The problem was the Swap memory. It wasn't enough and so the E2 was killing the process and restarting itself.
I managed to solve it  by creating a Swap memory file using Swap manager plugin and it worked.
So indeed it was NOT an e2m3u2bouquet issue.
Thank you very much though.
You really helped.
