### ISSUE TITLE
Unable to parse without tvg-id on 0.8.3

### ISSUE THREAD

**Issue by tadcrazio** [su1s/e2m3u2bouquet#107]
Consider the following sample playlist. 

> #EXTM3U
> #EXTINF:-1  tvg-id="BBC1.uk" group-title="UK - Entertainment",BBC1
> http://LinkToMyPlayList.com/playstreams//73656.mpegts
> 
> #EXTINF:-1  tvg-id="BBC1.uk" group-title="UK - Entertainment",BBC 1 HD
> http://LinkToMyPlayList.com/playstreams//73552.mpegts
> 
> #EXTINF:-1  tvg-id="BBC1.uk" group-title="UK - Entertainment",BBC 1 FHD
> http://LinkToMyPlayList.com/playstreams//109199.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC One Scotland
> http://LinkToMyPlayList.com/playstreams//80059.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC One Wales
> http://LinkToMyPlayList.com/playstreams//80061.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC 2
> http://LinkToMyPlayList.com/playstreams//73655.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC 2 HD
> http://LinkToMyPlayList.com/playstreams//73551.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC 2 FHD
> http://LinkToMyPlayList.com/playstreams//109198.mpegts
> 
> #EXTINF:-1   group-title="UK - Entertainment",BBC SCOTLAND
> http://LinkToMyPlayList.com/playstreams//73649.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC KSAT_SAA
> http://LinkToMyPlayList.com/playstreams//150019.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC 15 ARIZONA
> http://LinkToMyPlayList.com/playstreams//150008.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC 30 STLOUIS
> http://LinkToMyPlayList.com/playstreams//150009.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC 7 Washington
> http://LinkToMyPlayList.com/playstreams//150010.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC KABC_LAX
> http://LinkToMyPlayList.com/playstreams//150011.mpegts
> 
> #EXTINF:-1   group-title="USA - Regional",USA : ABC KATU_POR
> http://LinkToMyPlayList.com/playstreams//150012.mpegts

Not all EXTINF lines contain a tvg-id so not all bouquets will be created OR not all channels will be added due to the absence of a tvg-id. Simply added tvg-id "" to the playlist will work, but when working with a remote file this is not always convenient.

**Comment by lincsat** [comment]
I have exactly the same problem with a provider. What I do is to download the M3U file, then use find & Replace to replace #EXTINF:-1 group with #EXTINF:-1 tvg-id="" group. Then save the file to the box and use the local file location as the M3U URL. 

It is a pain to do every Day but works well until the panel sends a compliant file

**Comment by DougMac** [comment]
In v0.8.3 if a channel doesn't have any tvg parameters it will be ignored, this fixed an issue where the presence of these channels would cause the entire the script/plugin to fail.

This will be further tweaked in v0.8.4 so that these channels will be included in the bouquets.

**Comment by DougMac** [comment]
Should be fixed in [v0.8.4](https://github.com/su1s/e2m3u2bouquet/releases/tag/v0.8.4)
