### ISSUE TITLE
Will not parse 

### ISSUE THREAD

**Issue by andybez** [su1s/e2m3u2bouquet#108]
Hi my supplier has just added a new panel and suls script will not parse the file. 

It just sits parsing, I think it’s due to the issue  in the attachment.

Sorry for the bad marking up :-)

Thanks
![BC126DC3-EDAD-46E6-B6C7-0E4834544544](https://user-images.githubusercontent.com/56453183/66678261-6318d500-ec63-11e9-83e4-f60c017eed08.jpeg)

**Comment by DougMac** [comment]
This should be fixed in [v0.8.5](https://github.com/su1s/e2m3u2bouquet/releases/latest). If not please reopen this issue
