### ISSUE TITLE
File name normalization

### ISSUE THREAD

**Issue by pepsik-kiev** [su1s/e2m3u2bouquet#111]
**def get_safe_filename (filename):**
It does not work with NOT Latin characters. It is built on the basis of unicodedata.normalize, which is applicable to the European language groups based on the Latin alphabet. Moreover, you further do re.sub ('[^ a-z0-9-_]' - this is NOT necessary, because unicodedata.normalize has already done this, more precisely, "cleaned" the transmitted string from all invalid characters, why do you limit the file name to only letters and numbers? Is it somewhere in the standard?
 For example, try to parse this playlist
`#EXTINF:-1 group-title="Детские" tvg-name="В гостях у сказки" tvg-logo="http://192.168.2.50:8081/stat/picons/N076JCPKNaCl1T8ANnskFElL4t4uE8.png",В гостях у сказки `
`#EXTINF:-1 group-title="Детские" tvg-name="Мульт" tvg-logo="http://static.acestream.net/sites/acestream/img/ACE-logo.png",Мульт`
`#EXTINF:-1 group-title="Познавательные" tvg-name="Охотник и рыболов HD" tvg-logo="http://static.acestream.net/sites/acestream/img/ACE-logo.png",Охотник и рыболов HD`
And look at how you create bouquets. 
Somewhere in the standard, it is stipulated that the group-title tag, which you use to create userbouquet name, cannot contain letters of NOT Latin alphabetical alphabet? Or somewhere in the standard, it is provided that the file name can NOT be NOT Latin? Where in linux based systems is there such a limitation?
**Try in python console:**
`import unicodedata`
`filename = 'этоимяфайла'`
`unicodedata.normalize('NFKD', unicode(filename, 'utf_8')).encode('ASCII', 'ignore')`
`''`
`filename = 'thisisfilename'`
`unicodedata.normalize('NFKD', unicode(filename, 'utf_8')).encode('ASCII', 'ignore')`
`'thisisfilename'`

**Comment by DougMac** [comment]
unicodedata.normalize does not do the same as re.sub ('[^ a-z0-9-_]'

**Test**
filename = "filename/\?%*:|\"<>. "
return executing re.sub ('[^ a-z0-9-_]' = 'filename__'
return not executing re.sub ('[^ a-z0-9-_]' 'filename_\\?%*:|"<>._'

Obviously without the regex replacement the filename would be invalid which is why this is in place.

Yes, you've highlighted an issue if the entire name is not in ASCII it will fail which we'll potentially look at fixing in a future version.

**Comment by pepsik-kiev** [comment]
> unicodedata.normalize does not do the same

Ok  ... But then like this

`    import unicodedata
    value = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore')
    value = unicode(re.sub('[^\w\s-]', '', value).strip().lower())
    value = unicode(re.sub('[-\s]+', '-', value))`

 This is the "gold" standard for the Latin alphabet =) . Look at Django slugify() ...

**Comment by DougMac** [comment]
Closed. May consider for future release.
