### ISSUE TITLE
Invalid Service refernece

### ISSUE THREAD

**Issue by lincsat** [su1s/e2m3u2bouquet#112]
I'm finding that in some cases I'm getting invalid service refs. As you can see from below, the refs have a field containing more than the 4 character max allowed by Enigma2. The channels do still display but it breaks the EPG. Is it possible to limit each field to 4 characters?

```
<channel name="VIP HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc6:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
    <channel name="HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc7:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
    <channel name="VIP FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc8:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
    <channel name="FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc9:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
```

**Comment by DougMac** [comment]
I'll get this fixed in the next release.

**Comment by pepsik-kiev** [comment]
This error is most likely due to the fact that you have m3u with a very large number of channels or one of the groups contains more than 200 channels. Actually, the error is in the code because there is no restriction on the bit width of the TsID (4-digit HEX value) when forming the serviceref, as the standard prescribes
[https://wiki.tuxbox-neutrino.org/wiki/Enigma:Services:Formatbeschreibung](url)

**Comment by BliNeR-KeY** [comment]
> I'm finding that in some cases I'm getting invalid service refs. As you can see from below, the refs have a field containing more than the 4 character max allowed by Enigma2. The channels do still display but it breaks the EPG. Is it possible to limit each field to 4 characters?
> 
> ```
> <channel name="VIP HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc6:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
>     <channel name="HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc7:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
>     <channel name="VIP FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc8:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
>     <channel name="FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc9:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> ```

dhis issue is because from your source no have TS output.  e2m3u2bouquet support only MPEGTS output.  already i talk skype about dhis issue with @DougMac . 
dhis is not e2m3u2bouquet issue. 
solution = add access_output TS key.

**Comment by pepsik-kiev** [comment]
> > I'm finding that in some cases I'm getting invalid service refs. As you can see from below, the refs have a field containing more than the 4 character max allowed by Enigma2. The channels do still display but it breaks the EPG. Is it possible to limit each field to 4 characters?
> > ```
> > <channel name="VIP HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc6:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc7:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="VIP FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc8:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc9:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> > ```
> 
> dhis issue is because from your source no have TS output. e2m3u2bouquet support only MPEGTS output. already i talk skype about dhis issue with @DougMac .
> dhis is not e2m3u2bouquet issue.
> solution = add access_output TS key.

This is precisely the problem of the code, because it does not control and does not report in the logs that it does not comply with the standard, moreover, it allows the formation of serviceref that does not comply with the accepted standard. See the link in my previous post. Why should a user think about standards that are unknown to him and not interesting

**Comment by DougMac** [comment]
> > I'm finding that in some cases I'm getting invalid service refs. As you can see from below, the refs have a field containing more than the 4 character max allowed by Enigma2. The channels do still display but it breaks the EPG. Is it possible to limit each field to 4 characters?
> > ```
> > <channel name="VIP HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc6:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="HD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc7:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="VIP FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc8:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> >     <channel name="FHD Sky Sports Main Event" nameOverride="" tvg-id="skysportsmainevent.uk" enabled="true" category="VIP HD/FHD UK SPORTS" categoryOverride="" serviceRef="1:0:1:16fc9:f1e5:a4e9:0:0:0:0" clearStreamUrl="false" />
> > ```
> 
> dhis issue is because from your source no have TS output. e2m3u2bouquet support only MPEGTS output. already i talk skype about dhis issue with @DougMac .
> dhis is not e2m3u2bouquet issue.
> solution = add access_output TS key.

Hi, 

What we discussed regarding MPEGTS was an issue with one specific panel. Every other panel I've seen doesn't have this issue.

The OP issue is likely due to a change we made with the service ids for VOD streams which if you have a large number will exceed the max limit.

This will be fixed in the next release
