### ISSUE TITLE
Disable / ignore some channels possible?

### ISSUE THREAD

**Issue by mckay17** [su1s/e2m3u2bouquet#115]
Hi, very good job here, i like this plugin.

I want to ignore / disable some channels, maybe by Channelnumber or name, could this be possible and if yes how?

Or if i delete those channels manually, that it doesnt add them next time again?

Thank you

**Comment by DougMac** [comment]
Yes it's possible please see https://www.suls.co.uk/enigma2-iptv-bouquets-with-epg/e2m3u2bouquet-custom-mapping/

**Comment by mckay17** [comment]
mh okay i dont have the provider_name-sort-current.xml

How do i get it? :D I have to run the script first?! but how? ^^

**Comment by mckay17** [comment]
Works great, thank you
