### ISSUE TITLE
Override.xml is being parsed but has no effect

### ISSUE THREAD

**Issue by chumleychuff** [su1s/e2m3u2bouquet#116]
Hi - i'm using the plugin, I have an override.xml following instructions from here (https://www.suls.co.uk/enigma2-iptv-bouquets-with-epg/e2m3u2bouquet-custom-mapping/), the plugin screen says it is processing custom channel order on import but it has no effect on the bouquets (I have enabled="false" all the categories apart from 1) - can you help? 

Files I have:
[iptv-sort-current.zip](https://github.com/su1s/e2m3u2bouquet/files/3855410/iptv-sort-current.zip)

**Comment by DougMac** [comment]
Thanks for reporting the issue.

Looks like a recent update has caused this. We'll get it fixed in the next release.

**Comment by lincsat** [comment]
It could be that the override file is not following the xml protocol 100%.
Try using a validating editor to check for errors. I use this -
http://xml-copy-editor.sourceforge.net

**Comment by DougMac** [comment]
Hopefully fixed in [v0.8.5](https://github.com/su1s/e2m3u2bouquet/releases/latest). If not please reopen this issue
