### ISSUE TITLE
e2m3u2bouquet.py: UnicodeDecodeError

### ISSUE THREAD

**Issue by jvul** [su1s/e2m3u2bouquet#117]
I got the following error:
e2m3u2bouquet.py: UnicodeDecodeError('utf8', 'DK | TV2 \xd8stjylland HD', 9, 10, 'invalid continuation byte')

I searched in the m3u and found 
#EXTINF:-1 tvg-id="" tvg-name="DK | TV2 Østjylland HD" tvg-logo="" group-title="SCAN | Scandinavian",DK | TV2 Østjylland HD

The issue is probably the Ø. 
Can this be solved?

Regards,

**Comment by DougMac** [comment]
I'm expecting to release a new version in the next couple of days that will fix this.

**Comment by jvul** [comment]
Thanks

**Comment by DougMac** [comment]
This should be fixed in v0.8.5

**Comment by DougMac** [comment]
This should be fixed in [v0.8.5](https://github.com/su1s/e2m3u2bouquet/releases/latest). If not please reopen this issue
