### ISSUE TITLE
Small mod - selectable option of m3u or m3u_plus in GUI

### ISSUE THREAD

**Issue by pricklydevil** [su1s/e2m3u2bouquet#123]
Hi,

Just had a change of provider and the GUI would run as normal but no channels would work. Ran the PY and found that the provider was specifically asking for m3u_plus in the URL

----Parsing m3u file----
No extended playlist info found. Check m3u url should be 'type=m3u_plus'

As all the XC backends form "mostly" the same URL string, is it possible to get a option to change from m3u to m3u_plus in the GUI?

Cheers

**Comment by lincsat** [comment]
I believe it does request a M3U_Plus as standard. It sounds like the reply from your server isn't. Download the M3U locally and check it's format.

**Comment by pricklydevil** [comment]
Double checked and it's m3u_plus as the script suggested but it wanted the full XC URL including &type=m3u_plus.

Never seen that behaviour before from the script. Tried it on another person's OpenVIX box and got exactly the same thing on the same provider. Will ask them to investigate as well
