### ISSUE TITLE
Installation fails on latest OpenPli releases (dev)

### ISSUE THREAD

**Issue by LittleJoe-CH** [su1s/e2m3u2bouquet#125]
Hi,

Thanks for your fantastic plugin. infortuately it cannot be installed anymore in the latest OpenPLI releases. (Python version???) See below:

****
root@h9:~# opkg install /tmp/enigma2-plugin-extensions-e2m3u2bouquet_0.8.5_all.ipk
Installing python-image (2.7.13) on root
Downloading http://littlejoe.freeddns.org/feeds/openpli-dev/cortexa15hf-neon-vfpv4/python-image_2.7.13-r1_cortexa15hf-neon-vfpv4.ipk.
To remove package debris, try `opkg remove python-image`.
To re-attempt the install, try `opkg install python-image`.
Installing enigma2-plugin-extensions-e2m3u2bouquet (0.8.5) on root

********************************************
Installing Engima2 IPTV E2m3u2bouquet plugin
********************************************

Configuring enigma2-plugin-extensions-e2m3u2bouquet.

********************************************
Engima2 IPTV E2m3u2bouquet plugin installed
********************************************

********************************************
Restart box to complete install
********************************************
Collected errors:
 * check_data_file_clashes: Package python-image wants to install file /usr/lib/python2.7/lib-dynload/imageop.so
        But that file is already provided by package  * python-misc
***

**Comment by DougMac** [comment]
Looks to be a conflict on your box between the python-image and python-misc packages

You could try installing using `opkg install --force-depends https://github.com/su1s/e2m3u2bouquet/releases/download/v0.8.5/enigma2-plugin-extensions-e2m3u2bouquet_0.8.5_all.ipk`

or possibly` opkg install --nodeps https://github.com/su1s/e2m3u2bouquet/releases/download/v0.8.5/enigma2-plugin-extensions-e2m3u2bouquet_0.8.5_all.ipk` would work

**Comment by LittleJoe-CH** [comment]
![image](https://user-images.githubusercontent.com/65328665/83664776-c5e02780-a5ca-11ea-8e6a-b0c1e29c6b61.png)

unfortunately I get this error with --force-depends and with --nodeps.

**Comment by LittleJoe-CH** [comment]
For information, copying the imghdr.py module source file into the plugin directory (/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet) fixed my problem. Maybe add it to your installation ipk?
