### ISSUE TITLE
Custom bouquet names still forces 'IPTV - ' prefix

### ISSUE THREAD

**Issue by nicbedford** [su1s/e2m3u2bouquet#24]
nameOverride for bouquet names still forces 'IPTV -' prefix for the bouquet name. Some users may prefer bouquet names in a different format. e.g. Sports (IPTV), Movies (IPTV) rather than IPTV - Sports, IPTV - Movies.

When using nameOverride, bouquet should be named just with the contents of the override and not include the 'IPTV - ' prefix text.

**Comment by DougMac** [comment]
That's a good point. I'll get it updated

**Comment by DougMac** [comment]
Hopefully that should be fixed now
