### ISSUE TITLE
Module object has no attribute 'SSLcontext'

### ISSUE THREAD

**Issue by pictona** [su1s/e2m3u2bouquet#33]
Hi,

I have an older openvix box that cannot be updated but when I install the suls apk i get this error:

Some plugins are not available:
Extensions/E2m3ubouquet ('module' object has no attribute 'SSLcontext')

**Comment by DougMac** [comment]
The soon to be released v0.6.1 has a workaround for this (although unable to test if it works)

**Comment by pictona** [comment]
Awesome thanks. I am happy to test for you if you need.

**Comment by DougMac** [comment]
Workaround (hopefully) in the latest release v.0.6.1. Are you able test?

**Comment by pictona** [comment]
yer no problem. Can test today.

**Comment by pictona** [comment]
can confirm the error is no longer there and the plugin creates the bouquets. :)

**Comment by DougMac** [comment]
Thanks for testing and letting me know.
