### ISSUE TITLE
Allow plugin to be skinned via epg importer screens

### ISSUE THREAD

**Issue by kiddac** [su1s/e2m3u2bouquet#34]
A lot of skinners have skinned epg-importer for their skins. Therefore I think you should include this in your plugin.py.

EPGImportConfig and EPGImportLog are the latest equivalent screen for epg-importer.
EPGMainSetup and XLMTVImportLog are the old legacy xmltv importer names. 

In
class E2m3u2bConfig(ConfigListScreen, Screen):

add in the self.skinName
...
...
    def __init__(self, session, args = None):
        self.session = session
        Screen.__init__(self, session)
        **self.skinName = ["E2m3u2bConfig", "EPGImportConfig", "EPGMainSetup"]**

class E2m3u2bLog(Screen):
 ...
....
    def __init__(self, session):
        self.session = session
        Screen.__init__(self, session)
       **self.skinName = ["E2m3u2bLog", "EPGImportLog", "XMLTVImportLog"]**

**Comment by DougMac** [comment]
I've added the in v0.6.1 as a short term measure. It's likely the screens will be different from epg-importer in the future.

I'll see if I can find any recommendations for making enigma2 plugins easier to skin

**Comment by kiddac** [comment]
Thats why i put your own skin names in there (i just called it the same as your class name). It will first look for E2m3U2bConfig screen in the skin file. If that doesn't exist then it will look for EPG-importer screens. Failing all 3 will default to the skin layout you have put in your plugin.

Above gives you a good fallback, yours choice of name, epg-importer, xmltv-importer, default

**Comment by DougMac** [comment]
Thanks for the clarification - don't know how I missed that!

This is the first enigma2 plugin (or even Python coding) that I've done so it's all a learning experience for me.

(I'll need to read up on how enigma2 skinning works)
