### ISSUE TITLE
epg missing for some channels

### ISSUE THREAD

**Issue by tommycahir** [su1s/e2m3u2bouquet#37]
Hi Guys
I'm opening this on behalf of some users on e2comm forum who are reporting the issues
https://enigma2community.com/thread-450-post-2173.html#pid2173

**Summary - not all channels are getting the EPG data.**
_If I use Perfect Player on android and select the EPG source given by my provider, I get EPG for all channels.
When I select my provider (it rhymes with the American word for 'Taxi') in the Suls extension I don't get EPG for some channels... eg the Arabic Sports channels 1-11. It creates the source in EPGImporter and I have selected it._ 

_Yes the above post is whats happening with epg its importing epg on smart iptv app but subscript isn't pulling all epg channels for Arab sports or Portugal sports were it does using smart iptv app , it seems to only give UK channels is that correct ?_ 

I am not able to test this myself as I don't have the provider referenced

Regards
Tommy

**Comment by su1s** [comment]
Hi tommy, 

Know the provider, cant see any thing obviously wrong, any chance of a couple of affected channels to narrow things down ?

**Comment by DougMac** [comment]
It looks like for these channels the providers XMLTV epg feed only has a title set (the description is just <desc/>)

It would seem that Enigma2 or epg-importer (not sure which) ignores events with empty descriptions

**Comment by DougMac** [comment]
Closing due to issue being either with enigma2 or epg-importer
