### ISSUE TITLE
add support for ultrahd iptv please

### ISSUE THREAD

**Issue by jamesb1512** [su1s/e2m3u2bouquet#38]
http://catchup.ultrahd-iptv.co.uk:25461/get.php?username=USERNAME&password=PASSWORD&type=m3u_plus&output=ts
http://catchup.ultrahd-iptv.co.uk:25461/xmltv.php?username=USERNAME&password=PASSWORD

**Comment by su1s** [comment]
Done, please use the supplier form on the website in future..
Thanks
