### ISSUE TITLE
EPG defense

### ISSUE THREAD

**Issue by keratos68** [su1s/e2m3u2bouquet#42]
Well done guys. Just keeps getting better.

I have spotted a bug. This could be the python interpreter/complier or linux codebase on enigma2 boxes…

For some providers the Epg.xml source file can and often does contain tags all on one line , that is to say that tags are not delimited with CR and LF chars. So effevtively the epg guide is one huge long line. This is a problem as epg events are not parsed. The xml/etree parser seems to give up. What this means is that a seemingly perfect and legal epg.xml source file containing the channel IDs and then all the event info, is not parsed correctly and thus not displayed on the EPG for enigma2 boxes. This IS NOT a limitation of your script however there is an improvement that can be made to your script so that it can implement a defensive measure against these "bad" epg source files.

I have confirmed this on vix and ipab builds and confirmed the issue.

The fix is to ensure that there is a CR and LF after all closing tags. That means…

```
</Channel>
[insert CR and LF here , after EVERY tag instance; must be BOTH CR and LF because just one wont do it]
   ...
</Programme>
[insert CR and LF here , after EVERY tag instance; must be BOTH CR and LF because just one wont do it]
```

This seems to be a problem on some linux boxes but not all.

I used "sed" to insert the CR and LF characters after all occurrences of any of these above two tags. I simply put this into your python script. Anyway, after this all.worked fine. Could be done just as simply using regex in python:-

`sed 's/<\/[^>]*>/&\n/g' <epg-filename-before> <epg-filename-after>`

In fact, that command will format every ending tag, so much neater. And this really does fix the problem albeit a workaround rather than fixing the root cause. Hence I call this a defensive measure.

Please could you add this defensive measure so that ‘bad’ EPG source files can be processed , straight after the code that creates the epgimport files. What i did was download the epg epg source locally and then apply sed on it. Of course the .sources file your script creates, will need to then refer to the local epg file rather than the http://…. remote source file.

I used the twizted provider and grabbed the EPG before case (attached) which failed, then ran the above fix, modified the epg import files to point to the "after" case, and EPG then fully loaded.

EDIT: Wont let me upload the EPG i d/l from twizted provider.

**Comment by DougMac** [comment]
Issues with epg importer not this script / plugin. Closed.
