### ISSUE TITLE
Errors in bouquets

### ISSUE THREAD

**Issue by Loginbug** [su1s/e2m3u2bouquet#45]
Thanks for this program, but i have found a problem in generated bouquet:
https://pastebin.com/raw/eLPHwL6u
See the lines: #SERVICE 1:832:d:0:0:0:0:0:0:0:

**Comment by DougMac** [comment]
Those lines are channel placeholders to control the channel numbering.

If the IPTV bouquets are set to top then the first category channels will start at 101 next category at 200 and so on.

**Comment by Loginbug** [comment]
Maybe an option to disable this?

**Comment by DougMac** [comment]
Closing issue as not an error and is intended operation
