### ISSUE TITLE
Download providers bouquet (map custom service references) | do not work

### ISSUE THREAD

**Issue by Loginbug** [su1s/e2m3u2bouquet#47]
```
USERNAME="{USERNAME}";
PASSWORD="{PASSWORD}";
bouquet="{BOUQUET_NAME}";
m3u_url="{SERVER_URL}get.php?username=$USERNAME&password=$PASSWORD&type=m3u_plus&output={OUTPUT_KEY}";
xml_url="{SERVER_URL}xmltv.php?username=$USERNAME&password=$PASSWORD"

python /etc/enigma2/e2m3u2bouquet/e2m3u2bouquet.py -bd -bt -M -n "$bouquet" -m "$m3u_url" -e "$xml_url";
```

This is my command line, everything works exempt "download providers bouquet" function (-bd)".
This is the output code:

```
********************************
Starting Engima2 IPTV bouquets v0.7.0
2018-02-14 14:14:57.975936
********************************


----Downloading providers bouquet file----

----Downloading m3u file----

----Parsing m3u file----
Completed parsing data...

----Creating bouquets----
bouquets created ...

----Creating EPG-Importer config ----
EPG-Importer config created...

----Reloading bouquets----
bouquets reloaded...

********************************
Engima2 IPTV bouquets created !
********************************

To enable EPG data
Please open EPG-Importer plugin..
Select sources and enable the new IPTV source
(will be listed as NexTV under 'IPTV Bouquet Maker - E2m3u2bouquet')
Save the selected sources, press yellow button to start manual import
You can then set EPG-Importer to automatically import the EPG every day
```

Notice the "Downloading providers bouquet file"?
Let's see what list the program tries to download:

`Feb 14 14:23:30 daniele haproxy[30490]: *.*.*.*:47182 [14/Feb/2018:14:23:30.945] http get_php/get_php 0/0/10/21/+31 404 +187 - - ---- 1/1/1/0/0 0/0 {Mozilla/5.0 (Windows|} "GET /get.php?username=None&password=None&type=dreambox&output=ts HTTP/1.1"`

Yes, username=None and password=None

That's why this function do not works.

**Comment by DougMac** [comment]
You don't appear to be passing the username or password to the script (-u & -p parameters) which is required for the -bd option. Or if you want to specify the full url yourself you can use the -b option

**Comment by Loginbug** [comment]
I assume that program gets user and password from m3u_plus line.

**Comment by Loginbug** [comment]
I think that program should notice this config error.
