### ISSUE TITLE
Wrong SID parsing

### ISSUE THREAD

**Issue by Loginbug** [su1s/e2m3u2bouquet#48]
```
USERNAME="{USERNAME}";
PASSWORD="{PASSWORD}";
bouquet="{BOUQUET_NAME}";
m3u_url="{SERVER_URL}get.php?username=$USERNAME&password=$PASSWORD&type=m3u_plus&output={OUTPUT_KEY}";
xml_url="{SERVER_URL}xmltv.php?username=$USERNAME&password=$PASSWORD";
b_url="{SERVER_URL}get.php?username=$USERNAME&password=$PASSWORD&type=dreambox&output={OUTPUT_KEY}";

python /etc/enigma2/e2m3u2bouquet/e2m3u2bouquet.py -bt -M -n "$bouquet" -m "$m3u_url" -e "$xml_url" -bd -b "$b_url";
```

Let's have a look an example channel on a generated bouquests:
```
#SERVICE 1:0:1:106A:2008:FBFF:820000:0:0:0:http%3a//CENSORED.me%3a80/live/TEST/TEST/6867.ts:CHANNEL1
#DESCRIPTION CHANNEL1
```

It has wrong service id, that's the correct one:
```
#SERVICE 1:0:19:106A:2008:FBFF:820000:0:0:0:http%3A//CENSORED.me%3A80/live/TEST/TEST/6867.ts
#DESCRIPTION CHANNEL1
```

The third digit may not be 1.
I'm writing from Italy, we really need this plugin due to missing good epg servers for our channels. 
I would like to support your work.
Please fix this and tell me how to pay something for your work.
Thanks

**Comment by DougMac** [comment]
It should be using whatever service ref is in the panel's bouquet file (if using the -bd / -b option)

Whats services refs are listed in the output of
`http://[serverurl]/get.php?username=$USERNAME&password=$PASSWORD&type=dreambox&output=ts`

**Comment by Loginbug** [comment]
` http://[serverurl]/get.php?username=$USERNAME&password=$PASSWORD&type=dreambox&output=ts`
This url gives SID reported as an example before.

**Comment by DougMac** [comment]
Ok, I've checked this.

The third digit is not the the service id (that's the 4th digit) - the third digit is the service type (i.e. 0=Data, 1=TV, 2=Radio, 19=HD TV ). The service type has no impact for IPTV channels of epg mapping or.

Epg mapping used the 4th - 7th digit (SID:TID:NID:Namespace)

**Comment by DougMac** [comment]
Closing as doesn't appear to be an actual issue
