### ISSUE TITLE
Picons openwebif

### ISSUE THREAD

**Issue by gb160** [su1s/e2m3u2bouquet#49]
Hi, first off, excellent script...really taken the pain out of trying to get iptv with epg working on my enigma2.

Slight issue, the script successfully downloads all the icons, they're visible and working fine on the box itself, but in the openwebif interface I'm not getting any icons for IPTV channels in the bouquets added by the script.
Not sure if I'm doing anything wrong, apart from that it works perfectly.
I use openatv if thats any help. 

Cheers

**Comment by gb160** [comment]
It seems the issue is related to the naming of the picon pngs...if I make a duplicate icon and rename it to the service reference of the channel, it is displayed as it should.

Would it be possible to make this an option when running the script?

**Comment by DougMac** [comment]
Sorry but there are no plans to support service reference picons - only service name picons.

openwebif supports SNP with DVB channels so not sure why it doesn't like the IPTV ones.

**Comment by gb160** [comment]
Yeah I noticed that and thought it was a bit strange.
Not the end of the world, I'll just duplicate and rename the icons in my favourites bouquet, shouldn't take long and they're the only channels I tend to use.
Thanks anyway.

**Comment by DougMac** [comment]
Closing as no plans to support service reference picons due to the fact that service references are likely to change often for IPTV channels.

Would be good to see why openwebif doesn't support SNP for IPTV services but does for DVB and see if it can be fixed upstream
