### ISSUE TITLE
Support for Non-HTTP stream URLs

### ISSUE THREAD

**Issue by K3rm1t4** [su1s/e2m3u2bouquet#50]
First of all, tremendous job in putting this all together!

One enhancement I'd like to see is support for HTTPS, RTMP and maybe other stream types in M3U playlists. In the current version, URLs not prefixed by HTTP are skipped. 

Having just peaked at the code, I think this could be added rather easily through minor changes in the core parsing function.

I'd really appreciate if you'd find the time to implement this.
Thanks very much in advance for considering.

BR,
K.

**Comment by DougMac** [comment]
Should be easy enough add to add. We'll see if we can get this into the next release.
