### ISSUE TITLE
Using 0.7.1 beta got following error

### ISSUE THREAD

**Issue by bbbuk** [su1s/e2m3u2bouquet#51]
You may already know this but when I tried pre-release 0.7.1 beta (including latest .py update dated 24/02/18), but keep getting following error when going into "Providers" menu, it crashes few seconds after going into "Providers"

<   128.540> [Skin] Parsing embedded skin <embedded-in-'E2m3u2b_Providers'>
<   128.542> [Skin] processing screen <embedded-in-'E2m3u2b_Providers'>:
<   128.574> [Skin] processing screen SimpleSummary:
<   128.581> Traceback (most recent call last):
<   128.581>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/providers.py", line 95, in prepare
<   128.582>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/providersmanager.py", line 36, in read
<   128.583>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/providersmanager.py", line 80, in migration
<   128.583> AttributeError: ProvidersConfig instance has no attribute 'provider_name'
<   128.584> [ePyObject] (CallObject(<bound method E2m3u2b_Providers.prepare of <class 'Plugins.Extensions.E2m3u2bouquet.providers.E2m3u2b_Providers'>>,()) failed)

Before the BSOD, it just displays "please wait"

**Comment by DougMac** [comment]
Thanks for testing.

Should be fixed in the latest beta-3.ipk

The plugin version number hasn't changed so it will need installed with the opkg --force-reinstall option

**Comment by bbbuk** [comment]
I used the following ipk:
https://github.com/su1s/e2m3u2bouquet/releases/tag/v0.7.1-beta

But then re-compiled the main file, e2m3u2bouquet.py, to the latest version which you amended only  yesterday (24th).  I assume this is equivalent to beta-3? 

If it is, it made no difference, still crashes.

**Comment by DougMac** [comment]
You can download beta 3 from 
https://github.com/su1s/e2m3u2bouquet/releases/download/v0.7.1-beta/enigma2-plugin-extensions-e2m3u2bouquet_0.7.1_all-beta-3.ipk

e2m3u2bouquet.py doesn't contain any of the plugin code

**Comment by bbbuk** [comment]
Been trying this since yesterday.  So far ok.  Thanks.

Suggestion... When adding IPTV provider, there is no OK/Done coloured button.  Not a big deal as you can just press exit on remote to close that screen but others may have expected an ok button to close screen.

Can I clarify, when you enter M3U URL, can you just enter the first bit (ie: http://iptv-provider.com:80) or do you need the whole lot (ie: http://iptv-provider.com:80/get.php?username=USERNAME ...., etc .... )?

**Comment by DougMac** [comment]
The plugin will use AutoBouquetsMaker skins. The skin I'm using shows a save button

![add_provider_1](https://user-images.githubusercontent.com/5244899/36689881-a7c0bc08-1b28-11e8-8b06-5494b369e8be.png)

It currently needs the full url (idea is that people edit /etc/enigma2/e2m3u2bouquet/config.xml instead or trying to input urls with the remote). However being able to enter a shorter m3u url is a good enhancement / idea.

If you're upgrading from the older plugin it will attempt to migrate your settings to the config files setup

**Comment by bbbuk** [comment]
Sorry, i'm referring to the initial add screen before the configuring of it...

![m3uscreenshot](https://user-images.githubusercontent.com/15172287/36697461-07b34dcc-1b3f-11e8-9a21-384b046c7fb8.jpg)

**Comment by DougMac** [comment]
Ideally for that screen green would have been 'Ok' and yellow 'Add'. However to get it it to tie into existing skins I was limited in the buttons I could use. 

Another example is that when configuring a provider there is no delete button (you need to select the Delete: Yes config option and then save). These are compromises that I made but I think most people would like it to use existing skins

**Comment by DougMac** [comment]
Closing for now. Will see if anything can done on the UI in a future version
