### ISSUE TITLE
0.7.1 b3 couple of issues

### ISSUE THREAD

**Issue by lincsat** [su1s/e2m3u2bouquet#52]
Firstly, when using the separate user/pass option, the plugin freezes with the spinner displayed if the provider name does not 100% match the supported list. ie rapidiptv is OK, rapid iptv is not OK. It does work OK if the user and pass is included in the URL.

2nd, if the M3U is empty for any reason, eg incorrect user or pass, then Enigma2 crashes with the following in the log

----Parsing m3u file----<   567.229> 
<   567.230> [e2m3u2b] manual_update_callback Error: M3U file is empty. Check username & password
<   567.230> Traceback (most recent call last):
<   567.230>   File "/usr/lib/enigma2/python/mytest.py", line 235, in processDelay
<   567.234>     callback(*retval)
<   567.234>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/menu.py", line 126, in manual_update_callback
<   567.238> Exception: M3U file is empty. Check username & password
<   567.239> [ePyObject] (CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x732b5f08>>,()) failed)

**Comment by lincsat** [comment]
Yes, debug was enabled

**Comment by DougMac** [comment]
Should be fixed in the 0.7.1 release if not please re-open
