### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by wetpatch** [su1s/e2m3u2bouquet#53]
Hi, could you help with this. Many thanks.

root@vusolo2:~# cd /etc/enigma2/e2m3u2bouquet
root@vusolo2:/etc/enigma2/e2m3u2bouquet# ./e2m3u2bouquet.py -n FAB -u removed-p removed
Traceback (most recent call last):
  File "./e2m3u2bouquet.py", line 25, in <module>
    from PIL import Image
ImportError: No module named PIL
root@vusolo2:/etc/enigma2/e2m3u2bouquet#

**Comment by DougMac** [comment]
I've removed your username & password that you left in above (you may want to change your password)

Your box is missing some python libraries try running
`opkg install python-image python-imaging`

**Comment by wetpatch** [comment]
Many thanks.
