### ISSUE TITLE
picons from m3u

### ISSUE THREAD

**Issue by sentriz** [su1s/e2m3u2bouquet#6]
hello, fantastic script - the first thing that's actually worked for me after messing about for days, epg and all.

I was just wondering if the script would be able to extract the `tvg-logo` from  
`#EXTINF:-1 tvg-id="channel" tvg-name="name" tvg-logo="https://website/logo.png" group-title="thing",Name`
instead of looking in a local picons folder

thank you

**Comment by su1s** [comment]
Use the -P switch to extract picons from the m3u

**Comment by sentriz** [comment]
ah right I was mixing -P up with -q, thank you
