### ISSUE TITLE
Issue in some ServiceRef

### ISSUE THREAD

**Issue by BliNeR-KeY** [su1s/e2m3u2bouquet#62]
hello in some SRef have problem. on dhis way we lose a picon but still working EPG.

Original (9)
1:0:19:106A:2008:FBFF:820000:0:0:0:

from .xml (e2m3u2bouquet)
1:0:1:106a:2008:fbff:820000:0:0:0

from .tv (e2m3u2bouquet)
1:0:1:106a:2008:fbff:820000:0:0:0

**Comment by DougMac** [comment]
Is this using the 'Download providers bouquet' option to map custom service references that are set are in the providers panel?

This was designed for mapping local EPG data so it's only 1:0:19:**106A**:**2008**:**FBFF**:**820000**:0:0:0: (part in bold SID:TID:NID:Namespace) that needs to match.

For Picons we use service named references. If you want to use existing SRP ones then you could override the full service reference in the override file.

**Comment by BliNeR-KeY** [comment]
please check original.  1:0:19......
from .tv (e2m3u2bouquet) 1:0:1...........

if from .tv (e2m3u2bouquet) add missing 9 , picon working well.

**Comment by DougMac** [comment]
The question I'm asking is where is the 1:0:19 coming from. Are you using the the 'Download providers bouquet' option to map custom service references that are set are in the providers panel?

**Comment by BliNeR-KeY** [comment]
i dont know about panel .

but i know in original dvb provider and me compare some italian providers have sref x 1:0.19....

i try to my self edit line
https://github.com/su1s/e2m3u2bouquet/blob/master/e2m3u2bouquet.py#L298
                           x['serviceRef'] = "{}:0:19:{}:0:0:0".format(x['stream-type'], service_ref)
work perfect picon epg ...
 
i'm sure someother provider dont use 19. and use 1.

so i thing much petter to add alse 
                           x['serviceRef'] = "{}:0:19:{}:0:0:0".format(x['stream-type'], service_ref)

**Comment by BliNeR-KeY** [comment]
x['serviceRef'] = "{}:0:1:{}:0:0:0".format(x['stream-type'], service_ref) or  x['serviceRef'] = "{}:0:19:{}:0:0:0".format(x['stream-type'], service_ref)

**Comment by DougMac** [comment]
The script generates unique service refs so they're not going to match anyway unless you are using an override file or the 'Download providers bouquet' option.

So are you using an override file or the 'Download providers bouquet' option (-b or -bd option when using the script)?

**Comment by BliNeR-KeY** [comment]
In real I'm not using script at moment because plugin it's very stable in EGAMI image. I'm sure work well in all OE-A .And plugin have 0 issue. Working well everything. Just small issue On Italian provider in sref lose local picon. I only compare sref DVB origjinal from Italian provider using local picon and local EPG. I don't use external picon or external EPG. 

Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: DougMac <notifications@github.com> Data: 27/06/18  21:45  (GMT+01:00) A: su1s/e2m3u2bouquet <e2m3u2bouquet@noreply.github.com> Cc: BliNeR-KeY <blinerg@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [su1s/e2m3u2bouquet] Issue in some ServiceRef (#62) 
The script generates unique service refs so they're not going to match anyway unless you are using an override file or the 'Download providers bouquet' option.
So are you using an override file or the 'Download providers bouquet' option (-b or -bd option when using the script)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/su1s/e2m3u2bouquet","title":"su1s/e2m3u2bouquet","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/su1s/e2m3u2bouquet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DougMac in #62: The script generates unique service refs so they're not going to match anyway unless you are using an override file or the 'Download providers bouquet' option.\r\n\r\nSo are you using an override file or the 'Download providers bouquet' option (-b or -bd option when using the script)?"}],"action":{"name":"View Issue","url":"https://github.com/su1s/e2m3u2bouquet/issues/62#issuecomment-400806209"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/su1s/e2m3u2bouquet/issues/62#issuecomment-400806209",
"url": "https://github.com/su1s/e2m3u2bouquet/issues/62#issuecomment-400806209",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [su1s/e2m3u2bouquet] Issue in some ServiceRef (#62)",
"sections": [
{
"text": "",
"activityTitle": "**DougMac**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DougMac",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"su1s/e2m3u2bouquet\",\n\"issueId\": 62,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"su1s/e2m3u2bouquet\",\n\"issueId\": 62\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/su1s/e2m3u2bouquet/issues/62#issuecomment-400806209"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 350295492\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by DougMac** [comment]
So in the plugin provider settings do you have 'Check providers bouquet' set to 'enable' or 'disable'?

**Comment by BliNeR-KeY** [comment]
enable

**Comment by DougMac** [comment]
If you download your providers bouquet file from 
http://provider_url:port/get.php?username=USERNAME&password=PASSWORD&type=dreambox&output=ts

does it have all the correct service refs?

**Comment by BliNeR-KeY** [comment]
friend. trust me. 
if i send via terminal link same as your example i have epg and picon.
if i use e2m3u2bouquet i lose picon and not epg. 
its easy to undestand because missing 1:0:19: and not 1:0:1:....

for me personaly i solved add 9 in line #L298 #Col53.

**Comment by DougMac** [comment]
We won't be forcing to 1:0:19: instead of 1:0:1: so that's not an option.

The provider bouquet download option was designed for matching the epg not picons. At the moment you can use the override file to correct any service references that don't match your picons

**Comment by DougMac** [comment]
Closing issue, next release will use full service ref from providers bouquet file if it has any custom values
