### ISSUE TITLE
import egp data does not work

### ISSUE THREAD

**Issue by Tecko71** [su1s/e2m3u2bouquet#63]
Import epg data from iptv provider does not work. When I use epg importer no sources found. In android device the epg import works so it is a bug.

**Comment by DougMac** [comment]
If you get the message 'No active EPG sources found, nothing to do' in epg Importer then it sounds like you haven't enabled any source. 

The script will create a source with the provider name under 'IPTV Bouquet Maker - E2m3u2bouqet' which needs to be selected in epg importer

**Comment by DougMac** [comment]
Closing as epg is working fine. Could be a config issues or provider specific.

Re open if you can provider further details
