### ISSUE TITLE
Import of split VODs will not show up in <provider>-sort-current.xml

### ISSUE THREAD

**Issue by NicNull** [su1s/e2m3u2bouquet#66]
When importing a large iptv m3u_plus bundle with VOD in many different languages (incl XXX), without  -M option all pops into the VOD category, with -M option I get nice per country channel VOD bundles.
But, as I do not want to present the languages that I do not understand nor the triple x, 
I really need to filter them.

But even with -M option active, there is only one VOD category in the <provider>-sort-current.xml
<category name="VOD" nameOverride="" enabled="true" />

The bouquets:
IPTV - VOD - (V|EN) Movies - UK
IPTV - VOD - (V|SC) Movies - SC
... + 40 VOD more.

Any ideas?

**Comment by DougMac** [comment]
v0.8 has massively improved filtering speed so this could be something we look at in the future.
