### ISSUE TITLE
Command Line Users don't have bouquets reloaded in 0.8+

### ISSUE THREAD

**Issue by stingray82** [su1s/e2m3u2bouquet#84]
If operating from the command line on from another script, users don't get the bouquets reloaded as they never call reload_bouquets() like they do if using a config.xml

This can be successfully resolved by adding in at line 1627 the following two commands:
reload_bouquets()
display_end_msg()

First one to reload and the second to display your end message I assumed this is how you intended it, but got lost in the if else?

Without Modification:
![image](https://user-images.githubusercontent.com/11146912/50551460-834d4980-0c78-11e9-823c-967e97c2f298.png)
With Modification:
![image](https://user-images.githubusercontent.com/11146912/50551466-a4ae3580-0c78-11e9-8e90-4499d6e8148e.png)

Added Code in Situ:
![image](https://user-images.githubusercontent.com/11146912/50551481-dcb57880-0c78-11e9-8470-c84c844772a6.png)

**Comment by DougMac** [comment]
Thanks. I'll get this fixed int he next release
