### ISSUE TITLE
error with DESCRIPTION at the end of Stream url

### ISSUE THREAD

**Issue by blinddark** [su1s/e2m3u2bouquet#86]
Hello,
at first thanks for your script. Great tool!

There is an issue by creating the bouquet. If the tool creates the bouquet an Channel is written in two lines for Example Sky Sport Football HD from UK 
#SERVICE 4097:0:1:8d15:89fc:2784:0:0:0:0:httpurl:UK:: Sky Sport Football HD
#DESCRIPTION UK:: Sky Sport Football HD

Now the bouqued can't played from vu with VTI 14.
If you would change line 584 in the e2m3u2bouquet.py from
            f.write("#SERVICE {}:{}:{}\n"

to 
            f.write("#SERVICE {}:{}\n"

the first line ends with the httpurl and all works fine. 
#SERVICE 4097:0:1:8d15:89fc:2784:0:0:0:0:httpurl
#DESCRIPTION UK:: Sky Sport Football HD

Is it possible
[e2m3u2bouquet.zip](https://github.com/su1s/e2m3u2bouquet/files/2751430/e2m3u2bouquet.zip)

 to fix it in a next release? attached the changed .py file.

Best regards

**Comment by DougMac** [comment]
Thanks.

I'll test this and hopefully include in the next release
