### ISSUE TITLE
just create some bouquets?

### ISSUE THREAD

**Issue by blinddark** [su1s/e2m3u2bouquet#87]
Hello,

is it possible to to generate just some bouquets?  For example I just want to have the bouquets UK and US. At the moment I have to delete all other bouquets manually.

Best regards

**Comment by DougMac** [comment]
Yes, see the [usage of the override file](https://www.suls.co.uk/enigma2-iptv-bouquets-with-epg/e2m3u2bouquet-custom-mapping/)
