### ISSUE TITLE
parsing channels with xxx

### ISSUE THREAD

**Issue by dadoremix** [su1s/e2m3u2bouquet#88]
hello
i found your app for iptv parsing m3u to enigma2 box
or i have wrong config or its bug ?
parsing xxx channels 
after list is done, all is working, ony adults ch dont work
I use config to direct download m3u list to box
channel name is like
xxx: hustler hd

If i put from xtreame server full list
wget -O /etc/enigma2/iptv.sh "http://link........." && chmod 777 /etc/enigma2/iptv.sh && /etc/enigma2/iptv.sh

then all is working, but that is not that
i like your plugin

**Comment by dadoremix** [comment]
update
that is problem on black hole image 3.0.2-3.0.8 version
vu+ zero 
switch to openWIX . and problem solved
working all good

**Comment by DougMac** [comment]
It's likely the colon : in the channel name. The next release should fix the issue on black hole
