### ISSUE TITLE
Improvement: Add rtsp support as included example

### ISSUE THREAD

**Issue by stingray82** [su1s/e2m3u2bouquet#89]
**Lots of CCTV NVR's only support rtsp:**
This would allow users who have rtsp CCTV to host there own playlist and this then allows CCTV to be viewed on the box using the same script using the config file

**Example M3u below:**
https://raw.githubusercontent.com/stingray82/e2m3u2bouquet-tools/master/CCTV-M3U-Example/CCTV.m3u

**Code Changes Required:**
Change Line 908
elif 'http:' in line or 'https:' in line or 'rtmp:' in line:
to
elif 'http:' in line or 'https:' in line or 'rtsp:' in line or 'rtmp:' in line:

**Comment by DougMac** [comment]
Thanks. I'll add this to the next release

**Comment by DougMac** [comment]
Included in upcoming release v0.8.3
