### ISSUE TITLE
Some TS streams don't end in <dot>ts and are detected as VOD

### ISSUE THREAD

**Issue by oottppxx** [su1s/e2m3u2bouquet#92]
At least one provider has TS streams ending in .2ts instead of .ts. That makes them being detected as VOD, missing EPG.

The 1 character fix is to modify the check:
        if (parsed_stream_url.path.endswith('.ts') or parsed_stream_url.path.endswith('.m3u8')) \
to
        if (parsed_stream_url.path.endswith('ts') or parsed_stream_url.path.endswith('.m3u8')) \

**Comment by DougMac** [comment]
Thanks. I'll add this to the next version

**Comment by DougMac** [comment]
Fix included in upcoming release v0.8.3
