### ISSUE TITLE
Add support for Streaminy files

### ISSUE THREAD

**Issue by tommycahir** [su1s/e2m3u2bouquet#98]
Hi
When trying to use the plugin to parse an m3u from Streaminy panel the plugin fails at the parsing of the m3u file stage

Please update to handle support for https://streaminy.com/ playlists.

**Comment by tommycahir** [comment]
If you need some test links please let me know and I will send them on.

**Comment by lincsat** [comment]
I use a couple of servers now using Streaminy and the panel isn't
configured properly, one serves an invalid address in the M3U and the other
has http:// twice. I can download the M3U, edit it, store it locally, then
one loads fine but the other hangs like you suggest. The M3U looks correct,
don't know why the plugin hangs at parsing

**Comment by lincsat** [comment]
One of my servers has now fixed the domain served in the M3U and the plugin
is creating the bouquets properly. So there is nothing to fix in the
plugin, the server needs to fix the config in Streaminy

**Comment by tommycahir** [comment]
Do you mind sharing what changes were made so others can resolve the issue?

**Comment by lincsat** [comment]
The changes need making in the streaming panel itself, it needs configured
to serve the correct Domain. For example, one was set for - http://http://
When they changed this to a valid address, then it worked

**Comment by tommycahir** [comment]
actually upon further investigation it looks like their panel is adding a 2nd playlist extm3u section to the file generated.. closing as not e2m3u2bouquet issue

**Comment by DougMac** [comment]
@tommycahir Are you able to supply some sample links? It's possible we could add extra checks if these configuration issues are common.

**Comment by tommycahir** [comment]
Yeah I can get you some test lines, I'll email you an anonymized file to start with so you can see what I mean

**Comment by DougMac** [comment]
Reopen to look at playlists with multiple #EXTM3U sections

**Comment by DougMac** [comment]
Hopefully fixed in v0.8.3
