### ISSUE TITLE
Channel Numbering

### ISSUE THREAD

**Issue by Cofybreak** [su1s/e2m3u2bouquet#99]
From https://www.suls.co.uk/enigma2-iptv-bouquets-with-epg/e2m3u2bouquet-custom-mapping/

> The script will start the first service at channel number 101 with subsequent bouquets starting at the next 100 i.e. 200, 300. You can use placeholder services (from v0.8 on) to control the numbering within bouquets.

Why we need this function?
In addition, it does not work properly.
First channel in first bouquet start with 101, but in others start from 1.

**Comment by DougMac** [comment]
This is so that channel numbering can be manipulated to match an existing DVB channel number.
i.e. Some people may always want Channel 4 to be on channel 104.

**Comment by Cofybreak** [comment]
But some people may want every bouquet to start from number 1.
It is better to leave this in the hands of users, e.g. to start from 101 place line:

`<channel name="placeholder_100" category="e.g. Sports" />`
Placeholders at the end of bouquet hardly matter to anyone. So they can be left.

**Comment by DougMac** [comment]
Working as intended
